import type { ReactNode } from "react";
import Header from "./Header";
import Footer from "./Footer";
import { SideMenu } from "./Mobile";
import Head from "next/head";

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Nexample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className="container py-5">{children}</div>
      </main>
      <Footer />
      <SideMenu />
    </>
  );
}
